version: '3.4'

services:
  ultimate_tts:
    image: ultimate_tts
    stdin_open: true
    tty: true
    volumes:
      - .:/ultimate_tts
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]  
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: conda run --no-capture-output -n ultimate_tts /bin/sh "/ultimate_tts/train.sh"

  
volumes:
  ultimate_tts:
