version: '3.4'

services:
  ultimate_tts_gpu:
    image: ultimate_tts
    stdin_open: true
    tty: true
    volumes:
      - .:/ultimate_tts

    environment:
      - ULTIMATE_TTS_DIR=/ultimate_tts

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]  
    build:
      context: .
      dockerfile: ./Dockerfile.gpu

  ultimate_tts_cpu:
    image: ultimate_tts
    stdin_open: true
    tty: true
    volumes:
      - .:/ultimate_tts
    environment:
      - ULTIMATE_TTS_DIR=/ultimate_tts
    build:
      context: .
      dockerfile: ./Dockerfile.cpu

  
# volumes:
#   ultimate_tts:
